### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by TheJoshW** [tjjfvi/OctoPrint-IFTTT#1]
Hi,
Awesome plugin.  Just getting an issue when an event payload doesn't have 3 values.  See error below:
`2019-01-01 07:14:36,787 - octoprint.plugin - ERROR - Error while calling plugin IFTTT
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 230, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_IFTTT/__init__.py", line 29, in on_event
    payload = { "value1": values[0], "value2": values[1], "value3": values[2] }
IndexError: list index out of range`

**Comment by tjjfvi** [comment]
Hi @TheJoshW, thanks for letting me know! Could you send me a screencap of the settings interface and the values under `plugins.IFTTT.events` in your `config.yaml` (makerkeys redacted on both)? Also, did you edit the settings via the interface or via the `config.yaml`?

For right now, if you edit the `config.yaml` and fill in each of the `values` sections, adding ` - ''` to fill to three, it should resolve the issue while I fix it on my end.

**Comment by tjjfvi** [comment]
Actually, ignore me; I just realized where exactly this is broken, I'll let you know when it is fixed.

**Comment by tjjfvi** [comment]
Fixed in release 1.0.2.

@TheJoshW: to update now go to `Settings > Software Update > Advanced > Force check for update`.

**Comment by TheJoshW** [comment]
Nice work, thanks!
