### ISSUE TITLE
Feauture request: Attach image from camera

### ISSUE THREAD

**Issue by NickRimmer** [tjjfvi/OctoPrint-IFTTT#10]
Hello. I want to attach photo from camera.

There is you told about how to add link to local file
https://github.com/tjjfvi/OctoPrint-IFTTT/wiki/Sending-files-to-IFTTT

What if my photo path is like?
http://192.168.0.2:8080/?action=snapshot

**Comment by tjjfvi** [comment]
@NickRimmer: You can put that URL in IFTTT in a photo path or other file path value and it will follow the URL.
