### ISSUE TITLE
Time formatting

### ISSUE THREAD

**Issue by CyiDev** [tjjfvi/OctoPrint-IFTTT#12]
Everything is working great except when the plugin sends the .time variable it is in seconds only.  Looking for some way to preformat the time (hopefully hr:mm) before sending it to IFTTT.  IFTTT does not have a simple way to do ingredient math like /3600).toFixed(2).

**Comment by tjjfvi** [comment]
@CyiDev: I have added time formatting on the `beta` branch; could yo confirm it works?

To install, use this URL:
    https://github.com/tjjfvi/OctoPrint-IFTTT/archive/beta.zip

To use the formatted time, use `$t:.time`.

**Comment by CyiDev** [comment]
This is working now.  Thanks for adding it.

**Comment by tjjfvi** [comment]
@CyiDev: merged, released, and documented!
