### ISSUE TITLE
Any way to send the file name as a value

### ISSUE THREAD

**Issue by jbryson3** [tjjfvi/OctoPrint-IFTTT#13]
Great plugin! Just what I was looking for. Use case is to send me a SMS when my print is finished.

I'd love to get a message that says, "Butterfly_Box_Top just finished!"

Though I've read the Readme, and the wiki, I don't see an exhaustive list of available variables. It'd be great if one of them was .filename.

**Comment by jbryson3** [comment]
Nevermind, it appears, that's exactly what `.name` is for. I assumed it was for the name of the event, not the name of the file. It'd be great to enumerate all the possible values in a table in the docs somewhere.

**Comment by tjjfvi** [comment]
@jbryson3: [this page](http://docs.octoprint.org/en/master/events/index.html) lists all events and their payload properties.
