### ISSUE TITLE
IFTTT Integration not working

### ISSUE THREAD

**Issue by kenneking26** [tjjfvi/OctoPrint-IFTTT#15]
I am am unable to have octoprint communicate with webhooks. I have entered in the webhooks code as both OctoPrint-ClientOpened and op-ClientOpened with no use. I have followed the guide completly.

**Comment by tjjfvi** [comment]
Could you attach a screenshot of the settings page and the IFTTT Applet?

**Comment by tjjfvi** [comment]
Closing due to lack of response; feel free to comment and I’ll reopen it!
