### ISSUE TITLE
Cannot POST

### ISSUE THREAD

**Issue by tomac01** [tjjfvi/OctoPrint-IFTTT#17]
Hello, 

I always get the same error:

`
2019-10-28 20:42:41,212 - octoprint.plugins.IFTTT - INFO - v1
2019-10-28 20:42:41,213 - octoprint.plugins.IFTTT - INFO - v2
2019-10-28 20:42:41,215 - octoprint.plugins.IFTTT - INFO - v3
2019-10-28 20:42:41,218 - octoprint.plugins.IFTTT - INFO - sending a request to url: https://maker.ifttt.com/trigger//with/key/[REDACTED; biX.......], payload: {'value3': 'v3', 'value2': 'v2', 'value1': 'v1'}
2019-10-28 20:42:41,847 - octoprint.plugins.IFTTT - INFO - response: Cannot POST /trigger//with/key/biX......
`

The IFTTT app works well. I have tested them under the "Documentation" in IFTTT.

**Comment by TheKrush** [comment]
Where are you seeing that log? Mine worked once but then I changed the name of the event and it stopped working.

**Comment by TheKrush** [comment]
So apparently PrintDone, PrintStarted, PrintFailed will not work if renamed.

**Comment by tomac01** [comment]
@TheKrush: you can Download the log-File from the setting-menu.

I did not change the names.

**Comment by TheKrush** [comment]
Which log file though, I checked all of mine and none showed that message. Yours looks like it's missing the trigger.
`https://maker.ifttt.com/trigger/<should be something here>/with/key/`

What does it show for your trigger name for PrintDone in the plugin options?

**Comment by TheKrush** [comment]
I'm seeing what you're seeing now, sometimes it's missing the trigger name when it tries to post.
`2019-10-28 22:47:03,668 - octoprint.plugins.IFTTT - INFO - .port
2019-10-28 22:47:03,669 - octoprint.plugins.IFTTT - INFO - .baudrate
2019-10-28 22:47:03,680 - octoprint.plugins.IFTTT - INFO - 
2019-10-28 22:47:03,681 - octoprint.plugins.IFTTT - INFO - sending a request to url: https://maker.ifttt.com/trigger//with/key/[REDACTED; eKVebIeu...], payload: {'value3': '', 'value2': 115200, 'value1': u'/dev/MPSM-ALPHA'}`

**Comment by TheKrush** [comment]
I was looking at my config.yaml and I found the problem:
`  IFTTT:
    default_prefixes:
    - MPSM-ALPHA-
    events:
    - event_name: Connected
      trigger_names:
      - ''
      values:
      - .port
      - .baudrate
      - ''
    - event_name: Error
      trigger_names: []
      values:
      - .error
      - ''
      - ''
    - event_name: Disconnected
      trigger_names: []
      values:
      - ''
      - ''`

Instead of an empty array, it has a single trigger name that's an empty string. The plugin does not currently check for that. I'll put in a pull request for this to be fixed, but if you hardcode the trigger in there it should be fine.

**Comment by TheKrush** [comment]
Another temporary fix would be to either edit your config (which is what I did) `sudo nano /home/pi/.octoprint/config.yaml` and fix the empty trigger lines.
Or you can delete the rows in the settings in octoprint and readd them.

**Comment by tomac01** [comment]
Thank you so much! The tip with the trigger was just right. I have not entered anything here, because I thought that the pre-assignment is done by the plug-in. After I have entered something there it works now!

**Comment by TheKrush** [comment]
You should leave the issue open until the owner does the merge of the pull request, it's definitely still a bug others can be affected by. Not entering a value in there should still work based on how things are set up, you and I just found the edge case that makes it not work (I assume it's because we entered something in that field then deleted it).

**Comment by tomac01** [comment]
@TheKrush: you are right...

**Comment by tjjfvi** [comment]
@tomac01, @TheKrush: I merged #18 and released 1.2.1. If it’s not showing, you can force OctoPrint to reload it’s cache in the updates pane in settings.

@TheKrush: Thanks so much for diagnosing and addressing the issue!

**Comment by TheKrush** [comment]
Not a problem, happy to help.
