### ISSUE TITLE
Where can I learn more?

### ISSUE THREAD

**Issue by briancmoses** [tjjfvi/OctoPrint-IFTTT#2]
This isn't really an issue with anyone/anything other than me being ignorant.

I've been wanting to be able to automate some social media shares of my print jobs' time-lapse videos and this seems really promising to accomplish that goal,  but I'm ignorant and uninformed!  So far my experiments to use actions powered by IFTTT's webhooks with a GMail action have been unsuccessful

I'd be happy to help document a couple real-word examples in this projects wiki-space,  if someone can help me teach myself,  I'd be happy to throw together a couple examples and capture them in the wiki.

Please let me know how (or if) you want me to help!

**Comment by briancmoses** [comment]
Thanks!  This is a huge help to get me started and pointed in the right direction.  I appreciate the detailed response,  that's a lot of additional work to go through!

**Comment by tjjfvi** [comment]
Also, what I personally did to test sending the `PrintStarted` and `PrintDone` events was to upload an empty gcode file and "print" that.

**Comment by tjjfvi** [comment]
@briancmoses: FYI, the `dummy` part in \#6 is now no longer necessary.

**Comment by leolivier** [comment]
@tjjfvi great work!
But as you closed the issue, it's a bit hard to find now :)
May I ask you to copy paste this detailed answer somewhere in an MD document that can be linked to the readme.md on GitHub and also in the page on the octoprint repo?
That would be very useful for all those who try to find out how to get it working...
Thanks!

**Comment by tjjfvi** [comment]
@leolivier I had pulled most of the information into [this wiki page](https://github.com/tjjfvi/OctoPrint-IFTTT/wiki); is there anything else you think I should include? I'll add a link to the README and the plugin page soon.

**Comment by leolivier** [comment]
@tjjfvi , sorry, I didn't even think to look at the wiki :/

**Comment by tjjfvi** [comment]
Not a problem
