### ISSUE TITLE
display url that would be sent to ifttt

### ISSUE THREAD

**Issue by moltra** [tjjfvi/OctoPrint-IFTTT#21]
Can you add a display field that would show the URL that would be sent to ifttt as you update the fields.  This would make the setup easier.

**Comment by tjjfvi** [comment]
@moltra I’m sorry, I don’t understand. What URL are you talking about?

**Comment by moltra** [comment]
seeing what this plugin is actual sending to ifttt would be very beneficial.

**Comment by tjjfvi** [comment]
@moltra If you look in the `octoprint.log`, it says the URL it is requesting and will show if there is an error. I'd recommend double checking that the pi has internet connection and that you have the correct makerkey.

If it still isn't working, you can put an excerpt of the octoprint.log where it's trying to send the request to IFTTT here, and I can take a look.

**Comment by tjjfvi** [comment]
I'm closing this issue for housekeeping purposes; feel free to open another if the issue persists/recurs!
