### ISSUE TITLE
Plugin disabled on installation

### ISSUE THREAD

**Issue by mark-hahn** [tjjfvi/OctoPrint-IFTTT#22]
I'm having the same problem as in https://github.com/tjjfvi/OctoPrint-IFTTT/issues/3.  I did a successful install of  OctoPrint-IFTTT and rebooted.  The list of plugins on the bottom left of settings does not show  OctoPrint-IFTTT.  I tried rebooting the system five times and it still doesn't work.

The log has these  lines at verious places ...
```
| !OctoPrint-IFTTT (1.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_IFTTT

```

Any suggestions?

EDIT:  The plugin was diasabled.  Should a newly installed plugin be disabled?  I'll change the title of this issue.

**Comment by tjjfvi** [comment]
@mark-hahn No, that's strange. Had you installed it before and disabled it or something? Did you ever tell OctoPrint to disable all plugins/was it in safe mode?

**Comment by mark-hahn** [comment]
> Had you installed it before and disabled it or something?

Ah, that is probably the case.
