### ISSUE TITLE
Upgrade to support Python 3.*

### ISSUE THREAD

**Issue by mwilgar** [tjjfvi/OctoPrint-IFTTT#36]
Per various recommendations I've upgraded my Octopi to Python 3, but that broke this plugin gor me. Will you be upgrading it to support 3?

**Comment by tjjfvi** [comment]
This plugin already supports python 3, though I hadn't yet released it. Upgrading should now fix it; feel free to file another issue if the problem persists!

**Comment by mwilgar** [comment]
The upgrade feature doesn’t work as the documentation describes. The plugin manager reports there is no update available, and that the plugin is incompatible.

**Comment by tjjfvi** [comment]
OctoPrint caches the plugin update info for 24 hours; there should be a button to force refresh the update information under `Settings > OctoPrint > Software Update > Advanced > Force check for update`. If that doesn't work, you can try uninstalling and reinstalling the plugin.

**Comment by tjjfvi** [comment]
Actually, based on your other issue, you've already done this, so you can ignore ^ 🙂
