### ISSUE TITLE
1.3.0 Update reports that 1.2.1 was installed, causing repeated "update available" messages

### ISSUE THREAD

**Issue by mwilgar** [tjjfvi/OctoPrint-IFTTT#37]
After uninstalling and manually installing the 1.3.0 version, Octoprint is reporting that an update to 1.3.0 is available. After installing, Octoprint sees the current version as 1.2.1, causing the repeated upgrade message.

(Note the last image shows the installation reporting that it installed 1.2.1)

![image](https://user-images.githubusercontent.com/64931094/102362145-0a894a00-3f82-11eb-92e2-643e38504d16.png)

![image](https://user-images.githubusercontent.com/64931094/102363146-24775c80-3f83-11eb-9e7b-dd30161f095c.png)

![image](https://user-images.githubusercontent.com/64931094/102363272-440e8500-3f83-11eb-85ff-026eb3826ff5.png)

**Comment by TheKrush** [comment]
I'm experiencing this as well.

**Comment by tjjfvi** [comment]
Duh, forgot to bump the version. One min

**Comment by tjjfvi** [comment]
Published v1.3.1 (and actually bumped the version 😄 )
