### ISSUE TITLE
Set Time Format

### ISSUE THREAD

**Issue by seackone** [tjjfvi/OctoPrint-IFTTT#38]
Hi,
i think its not an issue, maybe im too stupid to set the correct time format as value.
If i set: .time to a value, I'll receive a message with the duration of the print in seconds. Now i want something like hours, minutes and seconds like you described in your configuration. I was following point 4:

If it begins with a dollar sign ($), it will:
If the second character is a t:
If the third character is s, it will format time in Hh Mm Ss format (e.g. 1h 2m 34s)

So my value is: $ts
right? Because I dont receive any messages anymore.

What I am doing wrong?

**Comment by tjjfvi** [comment]
I think your value should be `$ts.time`

**Comment by seackone** [comment]
wow. that was fast. thank you very much!

**Comment by tjjfvi** [comment]
I'm gonna close this for now; feel free to comment further or open a new issue if your problem persists.
