### ISSUE TITLE
Feature Request, allowing Octoprint to be the "that" statement 

### ISSUE THREAD

**Issue by EXOgreen** [tjjfvi/OctoPrint-IFTTT#6]
For example, I have a google home mini. I want to create an "applet" that works like so.

" Hey google, preheat my prusa for $ " where $ can be PLA, ABS, whatever I set in octoprint

which would send to octoprint to preheat to 215 degrees.  This would also allow me to take a job off the printer and tell it to reprint that job, or to print a predetermined file. 

I don't know how registering for all of that works at all, so I'm not going to be disappointed if it doesn't work.

**Comment by tjjfvi** [comment]
@EXOgreen: I have now put info into [this wiki page](https://github.com/tjjfvi/OctoPrint-IFTTT/wiki/OctoPrint-Actions).
